# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

#trigger:
#- main

#pool:
 # vmImage: ubuntu-latest

#steps:
#- script: echo Hello, world!
 # displayName: 'Run a one-line script'

#- script: |
 #   echo Add other tasks to build, test, and deploy your project.
  #  echo See https://aka.ms/yaml
 #displayName: 'Run a multi-line script'




#steps:
#- task: TerraformInstaller@0
 # inputs:
  #  terraformVersion: 'latest'

#- task: TerraformTaskV3@3
 # inputs:
  #  provider: 'azurerm'
   # command: 'init'
    #backendServiceArm: 'TestConnection'
   # backendAzureRmResourceGroupName: 'terraform-rg-ik'
  # backendAzureRmStorageAccountName: 'storagetfaccount'
  #  backendAzureRmContainerName: 'storagetfcontainer'
  #  backendAzureRmKey: 'terraform.tfstate'

#- task: TerraformTaskV3@3
#  inputs:
#    provider: 'azurerm'
#    command: 'apply'
 #   environmentServiceNameAzureRM: 'TestConnection'
#- script: |
#    echo Add other tasks to build, test, and deploy your project.
#    echo See https://aka.ms/yaml
 # displayName: 'Run a multi-line script'






trigger:
- main

name: Deploy Bicep files

variables:
  vmImageName: 'ubuntu-latest'
  var1: 'datafactory5xofiqqspqniu'
  var2: 'igkat12'
  var3: 'admin12xdas@F'
  var4: 'datafactory-vnet'
  var5: 'default'
  azureServiceConnection: 'APN DUIT(36c22809-a26c-4be9-905d-44b748bba1b0)'
  resourceGroupName: 'examplebicRG'
  location: 'westeurope'
  templateFile: 'main.bicep'
pool:
  vmImage: $(vmImageName)

steps:

- task: AzureCLI@2
  inputs:
    azureSubscription: 'APN DUIT(36c22809-a26c-4be9-905d-44b748bba1b0)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    arguments: '$(resourceGroupName) $(location) $(templateFile) $(var1) $(var2) $(var3) $(var4) $(var5)'
    inlineScript: 'az deployment group create --resource-group $(resourceGroupName) --template-file $(templateFile) $4 $1 $5 $6 $7 $2 $1 $8' 